### ISSUE TITLE
twice as many coins and powerups on COIN DASH

### ISSUE THREAD

**Issue by emikanter** [PacktPublishing/Godot-Game-Engine-Projects#23]
I checked all the code and couldn't find the problem, anyone having the same issue

**Comment by shruthis-shetty** [comment]
What exactly the issue? Can you give me more explanation on it?

**Comment by emikanter** [comment]
Well, it's just that. Everything works fine, the animations, etc.

But when I walks through a coin I get 2 points, when I get through the powerup I get 10 seconds.

I guess I have to learn how to share the whole project so the problem can be recognized :(

**Comment by cbscribe** [comment]
Indeed, without seeing your project, it's impossible to tell you why this is happening.

If you zip the project folder, you can attach it here.

**Comment by emikanter** [comment]
[CoinDash.zip](https://github.com/PacktPublishing/Godot-Game-Engine-Projects/files/6030789/CoinDash.zip)

there you go! thank you so much for your patience :D I love your book and I love godot

**Comment by cbscribe** [comment]
On your Coin.gd script, change:

	monitoring = false

to this:

	set_deferred("monitoring", false)

Explanation:

We disable the monitoring so that the coin can't be picked up "twice" because the overlap check fires again (due the the player still moving, for example). However, Godot doesn't like changing collision properties while it's in the middle of processing all the collisions, etc. In newer versions of Godot, it won't actually disable the monitoring, so you have to tell it to do so as soon as it is done with the collision handling, which is what `set_deferred()` does. It says "do this as soon as it's safe for you to do so".

**Comment by emikanter** [comment]
Thank you so much for this clarification
