### ISSUE TITLE
0:00:04:0344 - Error calling method from signal 'pickup': 'Node(Main.gd)::_on_Player_pickup': Method expected 1 arguments, but called with 0.

### ISSUE THREAD

**Issue by KoopHauss** [PacktPublishing/Godot-Game-Engine-Projects#8]
0:00:04:0344 - Error calling method from signal 'pickup': 'Node(Main.gd)::_on_Player_pickup': Method expected 1 arguments, but called with 0.
----------
Type:Error
Description: 
Time: 0:00:04:0344
C Error: Error calling method from signal 'pickup': 'Node(Main.gd)::_on_Player_pickup': Method expected 1 arguments, but called with 0.
C Source: core/object.cpp:1202
C Function: emit_signal

This is the error I keep getting but, cant seem to figure out what I'm doing wrong. I've attached a copy of my project I hope you have the time to take a look at it. Maybe you'll be able to spot what I'm missing.
I've only finished through adding the Powerup scene.
[Coin_Dash - Copy.zip](https://github.com/PacktPublishing/Godot-Game-Engine-Projects/files/2448993/Coin_Dash.-.Copy.zip)

**Comment by cbscribe** [comment]
In Player.gd, when you emit the pickup signal, you need to also include the object's `type` so that it can be handled by the `match` statement in Main.gd:

    emit_signal("pickup", "coin")

Note you're already doing this with the powerup:

    emit_signal("pickup", "powerup")

You will also want to make sure you pay close attention to capitalization. Your `match` statement in Main is checking "Coin" (capitalized) and "powerup" (not capitalized).

**Comment by KoopHauss** [comment]
I'd really like to thank you, because I've got other books on Godot that have a github reference and still haven't seen anything from those authors. Twice you've helped me and pretty much right away. Thank you much, I really do appreciate the help.
